from PIL import Image

image1 = Image.open('D:\\srini\\html_test1.jpeg')
image2 = Image.open('D:\\srini\\html_test2.jpeg')
image3 = Image.open('D:\\srini\\html_test3.jpeg')
image4 = Image.open('D:\\srini\\html_test4.jpeg')
image5 = Image.open('D:\\srini\\html_test5.jpeg')
image6 = Image.open('D:\\srini\\html_test6.jpeg')
image7 = Image.open('D:\\srini\\html_test7.jpeg')
image8 = Image.open('D:\\srini\\html_test8.jpeg')
image9 = Image.open('D:\\srini\\html_test9.jpeg')
image10 = Image.open('D:\\srini\\html_test10.jpeg')
image11 = Image.open('D:\\srini\\html_test11.jpeg')
image12 = Image.open('D:\\srini\\html_test12.jpeg')
image13 = Image.open('D:\\srini\\html_test13.jpeg')
image14 = Image.open('D:\\srini\\html_test14.jpeg')
image15 = Image.open('D:\\srini\\html_test15.jpeg')
image16 = Image.open('D:\\srini\\html_test16.jpeg')
image17 = Image.open('D:\\srini\\html_test17.jpeg')
image18 = Image.open('D:\\srini\\html_test18.jpeg')
image19 = Image.open('D:\\srini\\html_test19.jpeg')
image20 = Image.open('D:\\srini\\html_test20.jpeg')
image21 = Image.open('D:\\srini\\html_test21.jpeg')
image22 = Image.open('D:\\srini\\html_test22.jpeg')
image23 = Image.open('D:\\srini\\html_test23.jpeg')
image24 = Image.open('D:\\srini\\html_test24.jpeg')
image25 = Image.open('D:\\srini\\html_test25.jpeg')
image26 = Image.open('D:\\srini\\html_test26.jpeg')
image27 = Image.open('D:\\srini\\html_test27.jpeg')
 
im1 = image1.convert('RGB')
im2 = image2.convert('RGB')
im3 = image3.convert('RGB')
im4 = image4.convert('RGB')
im5 = image5.convert('RGB')
im6 = image6.convert('RGB')
im7 = image7.convert('RGB')
im8 = image8.convert('RGB')
im9 = image9.convert('RGB')
im10 = image10.convert('RGB')
im11 = image11.convert('RGB')
im12 = image12.convert('RGB')
im13 = image13.convert('RGB')
im14 = image14.convert('RGB')
im15 = image15.convert('RGB')
im16 = image16.convert('RGB')
im17 = image17.convert('RGB')
im18 = image18.convert('RGB')
im19 = image19.convert('RGB')
im20 = image20.convert('RGB')
im21 = image21.convert('RGB')
im22 = image22.convert('RGB')
im23 = image23.convert('RGB')
im24 = image24.convert('RGB')
im25 = image25.convert('RGB')
im26 = image26.convert('RGB')
im27 = image27.convert('RGB')


imagelist = [im2,im3,im4,im5,im6,im7,im8,im9,im10,im11,im12,im13,im14,im15,im16,im17,im18,im19,im20,im21,im22,im23,im24,im25,im26,im27]

im1.save(r'D:\\srini\\myhtml.pdf',save_all=True, append_images=imagelist)